// This file is part of the lizard quantum chemistry software.
// Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file at the root of the lizard source
// tree or at <https://github.com/KoehnLab/lizard/blob/main/LICENSE>.

#include "lizard/symbolic/TensorExpressions.hpp"

#include "Operation.hpp"

#include <memory>
#include <vector>

namespace lizard::itf {

/**
 * Takes the given expression tree and translates it into a sequence of ITF instructions.
 * The produced instruction sequence will only map the operations already contained in the
 * tree - in particular load, store, etc. operations are not generated by this method.
 */
[[nodiscard]] auto translate(const NamedTensorExprTree &tree) -> std::vector< std::unique_ptr< Operation > >;

} // namespace lizard::itf
