name: Build and test

on: [push, pull_request]

jobs:
    run:
        strategy:
            fail-fast: false
            matrix:
                build_type: [ Release, Debug ]
                os: [ ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022, macos-11, macos-12 ]

        runs-on: ${{ matrix.os }}
        # Don't run the pull_request triggered workflows, if the source branch lives in the main repo and
        # therefore triggered the push event already (aka: don't run the same workflow twice)
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1
                  submodules: 'recursive'

            - name: Get CMake
              uses: lukka/get-cmake@v3.20.1

            - name: Setup MSVC
              if: ${{ contains(matrix.os, 'windows') }}
              uses: ilammy/msvc-dev-cmd@v1

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  java-version: 11
                  distribution: 'temurin'

            - name: Install uuid-dev
              if: ${{ contains(matrix.os, 'ubuntu') }}
              run: sudo apt update && sudo apt install uuid-dev
              shell: bash

            - name: Build
              uses: lukka/run-cmake@v3
              with:
                  cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced' # Required to respect cmakeAppendedArgs
                  cmakeBuildType: ${{ matrix.build_type }}
                  buildDirectory: 'build'
                  cmakeAppendedArgs: -DLIZARD_LWYU=OFF -DLIZARD_IWYU=OFF -DLIZARD_CLANG_TIDY=OFF

            - name: Run tests
              run: cd build && ctest --output-on-failure .
