name: Build and test

on: [push, pull_request]

jobs:
    run:
        strategy:
            fail-fast: false
            matrix:
                build_type: [ Release, Debug ]
                os: [ ubuntu-18.04, ubuntu-20.04, windows-2019, windows-2022, macos-10.15, macos-11 ]
                include:
                    # Explicitly use a newer compiler on 18.04
                    - os: ubuntu-18.04
                      compiler: 'g++-9'

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1
                  submodules: 'recursive'

            - name: Get CMake
              uses: lukka/get-cmake@v3.20.1

            - name: Setup MSVC
              if: ${{ contains(matrix.os, 'windows') }}
              uses: ilammy/msvc-dev-cmd@v1

            - name: Setup Compiler
              if: ${{ matrix.compiler != '' }}
              run: echo "CXX=${{ matrix.compiler }}" >> $GITHUB_ENV

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  java-version: 11
                  distribution: 'temurin'

            - name: Install uuid-dev
              if: ${{ contains(matrix.os, 'ubuntu') }}
              run: sudo apt update && sudo apt install uuid-dev
              shell: bash

            - name: Build
              uses: lukka/run-cmake@v3
              with:
                  cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced' # Required to respect cmakeAppendedArgs
                  cmakeBuildType: ${{ matrix.build_type }}
                  buildDirectory: 'build'
                  cmakeAppendedArgs: -DLIZARD_LWYU=OFF -DLIZARD_IWYU=OFF

            - name: Run tests
              run: cd build && ctest --output-on-failure .
