name: General checks

on: [push, pull_request]

jobs:
    run:
        runs-on: ubuntu-latest
        # Don't run the pull_request triggered workflows, if the source branch lives in the main repo and
        # therefore triggered the push event already (aka: don't run the same workflow twice)
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1
                  submodules: 'recursive'
            
            - name: Check line endings
              uses: erclu/check-crlf@v1
              with:
                  exclude: '3rdParty/'

            - name: Generate compile-command DB
              run: mkdir build && cd build && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. && cd .. && ln -s build/compile_commands.json .
              shell: bash

            - name: Check code formatting
              uses: jidicula/clang-format-action@v4.6.2
              with:
                  clang-format-version: '10'
                  exclude-regex: '^(./3rdParty/*|./build/*)'
