name: General checks

on: [push, pull_request]

jobs:
    skip_test:
        runs-on: ubuntu-latest
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}
        steps:
            - id: skip_check
              uses: fkirc/skip-duplicate-actions@v5
              with:
                concurrent_skipping: same_content_newer
                skip_after_successful_duplicate: 'true'


    perform_general_checks:
        needs: skip_test

        if: needs.skip_test.outputs.should_skip != 'true'

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1
                  submodules: 'recursive'
            
            - name: Check line endings
              uses: erclu/check-crlf@v1
              with:
                  exclude: '3rdParty/'

            - name: Generate compile-command DB
              run: mkdir build && cd build && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. && cd .. && ln -s build/compile_commands.json .
              shell: bash

            - name: Check code formatting
              uses: jidicula/clang-format-action@v4.10.1
              with:
                  clang-format-version: '10'
                  exclude-regex: '^(./3rdParty/*|./build/*)'
