# Secure workflow with access to repository secrets and GitHub token for posting analysis results
name: Post the static analysis results

on:
  workflow_run:
    workflows: [ "Static analysis" ]
    types: [ completed ]

jobs:
  clang-tidy-results:
    # Trigger the job only if the previous (insecure) workflow completed successfully
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest


    steps:

        - name: 'Download artifact'
          uses: actions/github-script@v6
          with:
            script: |
              let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 run_id: context.payload.workflow_run.id,
              });
              let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
                return artifact.name == "clang-tidy-result"
              })[0];
              let download = await github.rest.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: matchArtifact.id,
                 archive_format: 'zip',
              });
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/clang-tidy-result.zip`, Buffer.from(download.data));

        - name: Set environment variables
          run: |
            mkdir clang-tidy-result
            unzip clang-tidy-result.zip -d clang-tidy-result
            echo "pr_id=$(cat clang-tidy-result/pr-id.txt)" >> $GITHUB_ENV
            echo "pr_head_repo=$(cat clang-tidy-result/pr-head-repo.txt)" >> $GITHUB_ENV
            echo "pr_head_ref=$(cat clang-tidy-result/pr-head-ref.txt)" >> $GITHUB_ENV

        - name: Check out PR
          uses: actions/checkout@v3
          with:
            repository: ${{ env.pr_head_repo }}
            ref: ${{ env.pr_head_ref }}
            persist-credentials: false

        - name: Redownload analysis result
          uses: actions/github-script@v6
          with:
            script: |
              let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 run_id: context.payload.workflow_run.id,
              });
              let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
                return artifact.name == "clang-tidy-result"
              })[0];
              let download = await github.rest.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: matchArtifact.id,
                 archive_format: 'zip',
              });
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/clang-tidy-result.zip`, Buffer.from(download.data));

        - name: Extract analysis results
          run: |
            mkdir clang-tidy-result
            unzip clang-tidy-result.zip -d clang-tidy-result

        - name: Run clang-tidy-pr-comments action
          uses: platisd/clang-tidy-pr-comments@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            clang_tidy_fixes: clang-tidy-result/fixes.yml
            pull_request_id: ${{ env.pr_id }}
