name: PR checks

on: [pull_request]


jobs:
  clang_tidy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
              fetch-depth: 1
              submodules: 'recursive'

        - name: Install clang-tidy
          run: sudo apt install clang-tidy
          shell: bash

        - name: Create compile_commands.json
          run: cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DLIZARD_BUILD_TESTS=OFF .
          shell: bash

        - name: Analyze
          run:  run-clang-tidy "$(pwd)/src/" "$(pwd)/include/" -export-fixes clang-tidy-fixes.yml -p build
          shell: bash

        - name: Run clang-tidy-pr-comments action
          uses: platisd/clang-tidy-pr-comments@v1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            clang_tidy_fixes: clang-tidy-fixes.yml
            request_changes: true
            suggestions_per_comment: 25
