name: PR checks

on: [pull_request]


jobs:
  clang_tidy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
              fetch-depth: 1
              submodules: 'recursive'

        - name: Install dependencies
          run: sudo apt install clang-tidy uuid-dev
          shell: bash

        - name: Setup Java
          uses: actions/setup-java@v3
          with:
              java-version: 11
              distribution: 'temurin'

          # As we depend on code generation, we have to build the project here in order to ensure all
          # required include files have been produced.
        - name: Build
          uses: lukka/run-cmake@v3
          with:
              cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced' # Required to respect cmakeAppendedArgs
              cmakeBuildType: Debug
              buildDirectory: 'build'
              cmakeAppendedArgs: -DLIZARD_LWYU=OFF -DLIZARD_IWYU=OFF -DLIZARD_CLANG_TIDY=OFF

        - name: Analyze
          run:  run-clang-tidy "$(pwd)/src/" "$(pwd)/include/" -export-fixes clang-tidy-fixes.yml -p build
          shell: bash

        - name: Run clang-tidy-pr-comments action
          uses: platisd/clang-tidy-pr-comments@v1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            clang_tidy_fixes: clang-tidy-fixes.yml
            request_changes: true
            suggestions_per_comment: 25
